logging:
  level:
    org.springframework.security: TRACE
server:
  error:
    include-stacktrace: never
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://koch-logistikshop.dev.lmis.de/auth/realms/vhv
